/***********************************************************************
MODULE:    UART
VERSION:   1.04
CONTAINS:  Routines for controlling the UART peripheral on the Philips
           P89LPC932A1
COPYRIGHT: Embedded Systems Academy, Inc. - www.esacademy.com
LICENSE:   May be freely used in commercial and non-commercial code
           without royalties provided this copyright notice remains
           in this file and unaltered
WARNING:   IF THIS FILE IS REGENERATED BY CODE ARCHITECT ANY CHANGES
           MADE WILL BE LOST. WHERE POSSIBLE USE ONLY CODE ARCHITECT
           TO CHANGE THE CONTENTS OF THIS FILE
GENERATED: On "May 11 2011" at "18:32:24" by Code Architect 2.06
***********************************************************************/

// SFR description needs to be included
#include <reg932.h>
#include "uart.h"

// flag that indicates if the UART is busy transmitting or not
static bit mtxbusy;

/***********************************************************************
DESC:    Initializes UART for mode 1
         Baudrate: 9600
RETURNS: Nothing
CAUTION: If interrupts are being used then EA must be set to 1
         after calling this function
************************************************************************/
sbit green = P2^7; // green button
sbit amber = P2^6; // amber button
sbit yellow = P2^5; // yellow button
sbit red = P2^4; // red button
void delay(long x)
{
	long i = 0;
	for(i;i<x;i++);
}
void uart_init
  (
  void
  )
{
  // configure UART
  // clear SMOD0
  PCON &= ~0x40;
  SCON = 0x50;
  // set or clear SMOD1
  PCON &= 0x7F;
  PCON |= (0 << 8);
  SSTAT = 0x00;

  // enable break detect
  AUXR1 |= 0x40;

  // configure baud rate generator
  BRGCON = 0x00;
  BRGR0 = 0xF0;
  BRGR1 = 0x02;
  BRGCON = 0x03;

  // TxD = push-pull, RxD = input
  P1M1 &= 0xFE;
  P1M1 |= 0x02;
  P1M2 &= 0xFD;
  P1M2 |= 0x01;

  // initially not busy
  mtxbusy = 0;

  // set isr priority to 0
  IP0 |= 0x10;
  IP0H |= 0x10;
  
  // enable uart interrupt
  ES = 1;
  EA = 1;

} // uart_init

/***********************************************************************
DESC:    UART Interrupt Service Routine
RETURNS: Nothing
CAUTION: uart_init must be called first
         EA must be set to 1
************************************************************************/
void uart_isr(void) interrupt 4 using 1
{
  if (RI)
  {
    // PUT CODE THAT EXECUTES WHEN RECEIVING A BYTE HERE
	char letter = uart_get();
	if(letter == 'L')
	{
		green = 0;
		delay(50000);
		green = 1;
	}
	if(letter == 'U')
	{
		amber = 0;
		delay(50000);
		amber = 1;
	}
	if(letter == 'C')
	{
		yellow = 0;
		delay(50000);
		yellow = 1;
	}
	if(letter == 'A')
	{
		red = 0;
		delay(50000);
		red = 1;
	}
	if(letter == 'S')
	{
		green = 0;
		delay(50000);
		green = 1;
	}
	if(letter == 'G')
	{
		amber = 0;
		delay(50000);
		amber = 1;
	}
	if(letter == 'E')
	{
		yellow = 0;
		delay(50000);
		yellow = 1;
	}
	if(letter == 'T')
	{
		red = 0;
		delay(50000);
		red = 1;
	}
	if(letter == 'a')
	{
		green = 0;
		delay(50000);
		green = 1;
	}
	if(letter == 'n')
	{
		amber = 0;
		delay(50000);
		amber = 1;
	}
	if(letter == '=')
	{
		yellow = 0;
		delay(50000);
		yellow = 1;
	}
     
    // clear interrupt flag
    RI = 0;
  } // if

  if (TI)
  {
    // clear interrupt flag
    TI = 0;
    // no longer busy
    mtxbusy = 0;
  } // if

} // uart_isr

/***********************************************************************
DESC:    Transmits a 8-bit value via the UART in the current mode
         May result in a transmit interrupt if enabled.
RETURNS: Nothing
CAUTION: uart_init must be called first
************************************************************************/
void uart_transmit(char c)
{
  while(mtxbusy);
  mtxbusy = 1;
  SBUF = c;
} // uart_transmit

/***********************************************************************
DESC:    Gets a received 8-bit value from the UART
RETURNS: Received data
CAUTION: uart_init must be called first
************************************************************************/
unsigned char uart_get
  (
  void
  )
{
  return SBUF;
} // uart_get